# Generated by Django 2.2.13 on 2021-11-17 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0055_auto_20200921_1722'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='name_fi',
        ),
        migrations.RemoveField(
            model_name='product',
            name='description_fi',
        ),
        migrations.RemoveField(
            model_name='product',
            name='title_fi',
        ),
    ]
