# Generated by Django 2.2.13 on 2021-11-20 20:09

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_auto_20181115_1953'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_status',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Order Placed', 'Order Placed'), ('Order Processing', 'Order Processing'), ('Shipped', 'Shipped'), ('Delivered', 'Delivered')], default='', max_length=47),
        ),
    ]
